#!/usr/bin/env bash
# Usage: istioenv version-file [<dir>]
# Summary: Detect the file that sets the current istioenv version
set -e
[ -n "$ISTIOENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.istio-version" ]; then
      echo "${root}/.istio-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$ISTIOENV_DIR" || {
    [ "$ISTIOENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${ISTIOENV_ROOT}/version"
fi
