#!/usr/bin/env bash
# Usage: istioenv completions <command> [arg1 arg2...]

set -e
[ -n "$ISTIOENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  istioenv-help --usage completions >&2
  exit 1
fi

# Provide istioenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec istioenv-commands
fi

COMMAND_PATH="$(command -v "istioenv-$COMMAND" || command -v "istioenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide istioenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
