#!/usr/bin/env bash
#
# Summary: Run istio with the selected version
#
# Usage: istioenv exec <command> [arg1 arg2...]
#
# Runs istio or tiller by first preparing PATH so that the selected
# version's `bin' directory is at the front.
#
# For example, if the currently selected istio version is 1.11.3:
#   istioenv exec istio version
#   istioenv exec tiller -version
#
# is equivalent to:
#   PATH="$ISTIOENV_ROOT/versions/1.11.3/bin:$PATH" istio version

set -e
[ -n "${ISTIOENV_DEBUG}" ] && set -x

export CMD=$1
if [ -z "${CMD}" ]; then
  echo "istioenv: command is not specified" >&2
  exit 1
fi

shift

export BIN_PATH=$(istioenv-bin-path)
if [ -z "${BIN_PATH}" ]; then
  exit 1
fi

export CMD_FULL="${BIN_PATH}/${CMD}"
if [ ! -x "${CMD_FULL}" ]; then
  echo "istioenv: command not found: ${CMD}" >&2
  exit 1
fi

exec "${CMD_FULL}" "${@}"
