#!/usr/bin/env bash
# Summary: Show the current istio version
set -e
[ -n "$ISTIOENV_DEBUG" ] && set -x

if [ -z "$ISTIOENV_VERSION" ]; then
  ISTIOENV_VERSION_FILE="$(istioenv-version-file)"
  ISTIOENV_VERSION="$(istioenv-version-file-read "$ISTIOENV_VERSION_FILE" || true)"
fi

if [ -z "$ISTIOENV_VERSION" ] || [ "$ISTIOENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${ISTIOENV_ROOT}/versions/${version}" ]
}

if version_exists "$ISTIOENV_VERSION"; then
  echo "$ISTIOENV_VERSION"
elif version_exists "${ISTIOENV_VERSION#istio-}"; then
  echo "${ISTIOENV_VERSION#istio-}"
else
  echo "istioenv: version \`$ISTIOENV_VERSION' is not installed (set by $(istioenv-version-origin))" >&2
  exit 1
fi
