#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific istio version
#
# Usage: istioenv local <version>
#        istioenv local --unset
#
# Sets the local application-specific istio version by writing the
# version name to a file named `.istio-version'.
#
# When you run a istio command, istioenv will look for a `.istio-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, istioenv will use the global istio version
# specified with `istioenv global'. A version specified with the
# `ISTIOENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a istio version known to istioenv.
# The special version string `system' will use your default system istio.
# Run `istioenv versions' for a list of available istio versions.

set -e
[ -n "$ISTIOENV_DEBUG" ] && set -x

# Provide istioenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec istioenv-versions --bare
fi

ISTIOENV_VERSION="$1"

if [ "$ISTIOENV_VERSION" = "--unset" ]; then
  rm -f .istio-version
elif [ -n "$ISTIOENV_VERSION" ]; then
  istioenv-version-file-write .istio-version "$ISTIOENV_VERSION"
else
  if version_file="$(istioenv-version-file "$PWD")"; then
    istioenv-version-file-read "$version_file"
  else
    echo "istioenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
